name: CI Tests

on:
  push:
    branches: [ main, master, dev_test_*, feature/* ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering


jobs:
  test:
    name: Test on ${{ matrix.os }} with Perl ${{ matrix.perl }}
    runs-on: ${{ matrix.os }}
    env:
      AUTOMATED_TESTING: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        perl: ["5.8","latest"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Show Perl version
      run: perl -V

    - name: Install dependencies
      run: |
        cpanm --installdeps --notest .
        
    - name: Build and test
      run: |
        cpanm --test-only -v .

  test-freebsd:
    name: Test on FreeBSD
    runs-on: ubuntu-latest
    # 'false' to disable FreeBSD tests
    if: false
    env:
      AUTOMATED_TESTING: 1

    steps:
    - uses: actions/checkout@v4

    - name: Test on FreeBSD
      uses: vmactions/openbsd-vm@v1
      with:
        envs: 'AUTOMATED_TESTING'
        usesh: true
        copyback: false
        prepare: |
          perl -V
        run: |
          perl Makefile.PL
          make test
